//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.FizzBuzzService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FizzBuzzService.IFizzBuzz")]
    public interface IFizzBuzz {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFizzBuzz/DoFizzBuzz", ReplyAction="http://tempuri.org/IFizzBuzz/DoFizzBuzzResponse")]
        string DoFizzBuzz(string Number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFizzBuzz/DoFizzBuzz", ReplyAction="http://tempuri.org/IFizzBuzz/DoFizzBuzzResponse")]
        System.Threading.Tasks.Task<string> DoFizzBuzzAsync(string Number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFizzBuzzChannel : Services.FizzBuzzService.IFizzBuzz, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FizzBuzzClient : System.ServiceModel.ClientBase<Services.FizzBuzzService.IFizzBuzz>, Services.FizzBuzzService.IFizzBuzz {
        
        public FizzBuzzClient() {
        }
        
        public FizzBuzzClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FizzBuzzClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FizzBuzzClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FizzBuzzClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoFizzBuzz(string Number) {
            return base.Channel.DoFizzBuzz(Number);
        }
        
        public System.Threading.Tasks.Task<string> DoFizzBuzzAsync(string Number) {
            return base.Channel.DoFizzBuzzAsync(Number);
        }
    }
}
